local M = {}

M.OK = "OK"
M.RANK_INIT_FAIL = "RANK_INIT_FAIL"
M.RANK_SERVICE_CACHE_FAIL = "RANK_SERVICE_CACHE_FAIL"
M.RANK_SERVICE_TIMEOUT = "RANK_SERVICE_TIMEOUT"
M.RANK_SERVICE_CALL_FAIL = "RANK_SERVICE_CALL_FAIL"
M.NOT_IN_RANK = "NOT_IN_RANK"
M.SAVE_DB_FAIL = "SAVE_DB_FAIL"

return M
